name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -o chatgpt-bot ./cmd/main.go

    - name: Deploy
      run: |
        export TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
        export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        ./chatgpt-bot
